###
### GET /categories
GET http://localhost:3001/categories
Content-Type: application/json
Authorization: Bearer <token>

### POST /categories
POST http://localhost:3001/categories
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Jambo e Ruivão"
}