###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "secret_user"
}

###
GET http://localhost:3001/login/role
Content-Type: application/json
Authorization: Bearer: <token>