### POST /post
POST http://localhost:3001/post
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "C++ is hard to easy!",
  "content": "The best thing about TypeScript is that it's a superset of JavaScript.",
  "image": "https://www.google.com",
  "categoryIds": [4, 5]
}

### GET /post
GET http://localhost:3001/post
Content-Type: application/json
Authorization: Bearer <token>


### GET /post/:id
GET http://localhost:3001/post/1
Content-Type: application/json
Authorization: Bearer <token>

### PUT /post/:id
PUT http://localhost:3001/post/1
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "TypeScript Super Set is the best of world!",
  "content": "The TypeScript is the best thing about TypeScript is that it's a superset of JavaScript.",
  "image": "https://www.google.com/typescript/2"
}

### DELETE /post/:id
DELETE http://localhost:3001/post/1
Content-Type: application/json
Authorization: Bearer <token>