### `POST /login`
POST http://localhost:3001/user
Content-Type: application/json

{
  "username": "Rafael Guedes",
  "email": "rafael@email.com",
  "password": "123456",
  "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png",
  "role": "admin"
}

### `GET /user`
GET http://localhost:3001/user
Authorization: Bearer <token>

### `GET /user/:id`
GET http://localhost:3001/user/1
Authorization: Bearer <token>

### `PUT /user/:id`
PUT http://localhost:3001/user/2
Content-Type: application/json
Authorization: Bearer <token>

{
  "username": "Rafael Tavares",
  "email": "rafamaga@hotmail.com",
  "password": "123456",
  "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png",
  "role": "admin"
}


### `DELETE /user/:id`
DELETE http://localhost:3001/user/4
Authorization: Bearer <token>